Controllers/AuthorController.cs
using LibrarySystem.Data;
using LibrarySystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibrarySystem.Controllers
{

    public class AuthorController : Controller
    {

        private readonly ApplicationDbContext _db;
        public AuthorController(ApplicationDbContext db)
        {
            _db = db;
        }



        public IActionResult Index()
        {
            IEnumerable<Author> objList = _db.Authors;
            return View(objList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Author obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Author Author)
        {
            if (ModelState.IsValid)
            {
                _db.Authors.Add(Author);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Author);
        }


        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Author obj = _db.Authors.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Author Author)
        {

            if (ModelState.IsValid)
            {
                if (Author == null)
                {
                    return NotFound();
                }
                _db.Authors.Update(Author);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Author);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Author obj = _db.Authors.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Author auth)
        {

            Author author = _db.Authors.Find(auth.AuthorId);

            _db.Authors.Remove(author);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Controllers/BookController.cs
using LibrarySystem.Data;
using LibrarySystem.Models;
using LibrarySystem.Models.DataVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibrarySystem.Controllers
{

    public class BookController : Controller
    {

        private readonly ApplicationDbContext _db;
        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }



        public IActionResult Index()
        {
            DateTime dt = DateTime.Now.Date;
            DateTime DueDate = dt.AddDays(7);

            IEnumerable<Book> objList = _db.Books;
            return View(objList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            Book obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book BookVM)
        {        
            if (ModelState.IsValid)
            {
                BookVM.isAvailable = Convert.ToBoolean(BookVM.isAvailable);
                _db.Books.Add(BookVM);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            return View(BookVM);
        }


        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Book obj = _db.Books.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }
        
        public IActionResult Show(int? id)
        {
            
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Book obj = _db.Books.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Book BookVM)
        {

            if (ModelState.IsValid)
            {
                if (BookVM == null)
                {
                    return NotFound();
                }
                _db.Books.Update(BookVM);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            return View(BookVM);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Book obj = _db.Books.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Authors.Select(i => new SelectListItem
            {
                Text = i.AuthorName,
                Value = i.AuthorId.ToString()
            });
            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Book Book)
        {
            int id = Book.BookId;
            Book book = _db.Books.Find(id);

            _db.Books.Remove(book);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Controllers/MemberController.cs
using LibrarySystem.Data;
using LibrarySystem.Models;
using LibrarySystem.Models.DataVM;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibrarySystem.Controllers
{

    public class MemberController : Controller
    {

        private readonly ApplicationDbContext _db;
        public MemberController(ApplicationDbContext db)
        {
            _db = db;
        }



        public IActionResult Index()
        {
            IEnumerable<Member> objList = _db.Members;
            return View(objList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Member obj = new();
            return View(obj);
        }

        [HttpPost]
       // [ValidateAntiForgeryToken]
        public IActionResult Create(MemberVM memberVM)
        {
            if (ModelState.IsValid)
            {
                Member member = new();
                member.MemberName = memberVM.MemberName;
                member.OtherCountry = memberVM.OtherCountry;
                member.MemberGender = memberVM.MemberGender;
                member.PhoneNumber = memberVM.PhoneNumber;
                member.SSN = memberVM.SSN;
                member.LibraryName = memberVM.LibraryName;
                member.languagesKnown = memberVM.languagesKnown;
                member.Profession = memberVM.Profession;
                member.City = memberVM.City;
                member.StreetAddress = memberVM.StreetAddress;
                member.Country = memberVM.Country;
                member.OtherCountry = memberVM.OtherCountry;
                member.MemberTypeId = memberVM.MemberTypeId;
                member.Email = memberVM.Email;
                member.MemberDOB = DateTime.Parse(memberVM.MemberDOB);
                _db.Members.Add(member);
                _db.SaveChanges();
                //return RedirectToAction("Index");
                return Ok();
            }
            return View(memberVM);
        }


        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Member obj = _db.Members.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(MemberVM memberVM)
        {

            if (ModelState.IsValid)
            {
                if (memberVM == null)
                {
                    return NotFound();
                }
                Member member = new();
                member.MemberId = memberVM.MemberId;
                member.MemberName = memberVM.MemberName;
                member.MemberGender = memberVM.MemberGender;
                member.PhoneNumber = memberVM.PhoneNumber;
                member.Profession = memberVM.Profession;
                member.City = memberVM.City;
                member.StreetAddress = memberVM.StreetAddress;
                member.Country = memberVM.Country;
                member.Email = memberVM.Email;
                member.MemberDOB = DateTime.Parse(memberVM.MemberDOB);
                member.OtherCountry = memberVM.OtherCountry;
                _db.Members.Update(member);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(memberVM);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is <= 0 or null)
            {
                return NotFound();
            }

            Member obj = _db.Members.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(MemberVM memberVM)
        {
            int id = memberVM.MemberId;
            Member member = _db.Members.Find(id);

            _db.Members.Remove(member);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibrarySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
</head>
<body class="custom-bg">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-md navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand font-weight-bolder text-warning" asp-area="" asp-controller="Home" asp-action="Index">LibrarySystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="BookAllocation" asp-action="Index">Allocations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Membertype" asp-action="Index">Others</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2021 - LibrarySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-warning">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/notify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>